apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fraud-sentinel
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - services.yaml
  - api-deployment.yaml
  - agent-deployment.yaml
  - ui-deployment.yaml
  - migration-job.yaml
  - rag-seed-job.yaml
  - trainer-job.yaml
  - retrain-cronjob.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - grafana-dashboard-configmap.yaml
