apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/ixxet/fraud-sentinel-api
    newTag: "b769b1c"
  - name: ghcr.io/ixxet/fraud-sentinel-trainer
    newTag: "04a84a0"
  - name: ghcr.io/ixxet/fraud-sentinel-ui
    newTag: "b769b1c"
patches:
  - path: ui-loadbalancer-patch.yaml
  - path: resource-patch.yaml
