apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: FRAUD_ENV
              value: talos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-ui
spec:
  template:
    spec:
      containers:
        - name: ui
          env:
            - name: NODE_ENV
              value: production

